---
abstract: 'Take any data source and deliver it to the world'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Aspect: 0.14
  ExtUtils::MakeMaker: 6.42
  File::Remove: 1.42
  File::Spec: 0.80
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.86'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Xtract
name: Xtract
no_index:
  directory:
    - inc
    - t
requires:
  DBD::SQLite: 1.25
  DBI: 1.57
  File::Remove: 1.42
  Getopt::Long: 2.37
  IO::Compress::Bzip2: 2.008
  IO::Compress::Gzip: 2.008
  Object::Tiny: 1.06
  Params::Util: 0.35
  Time::Elapsed: 0.24
  Time::HiRes: 1.9709
  perl: 5.8.5
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Xtract
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Xtract
version: 0.07
