---
abstract: 'Take any data source and deliver it to the world'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.56
  File::Remove: 1.42
  File::Spec: 0.80
  IO::Uncompress::Bunzip2: 0
  IO::Uncompress::Gunzip: 0
  Test::Database: 1.09
  Test::More: 0.42
  Test::NoWarnings: 0.084
  Test::Script: 1.03
configure_requires:
  ExtUtils::MakeMaker: 6.56
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Xtract
name: Xtract
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DBD::SQLite: 1.25
  DBI: 1.57
  File::Copy: 0
  File::Remove: 1.42
  File::Which: 0.05
  Getopt::Long: 2.37
  IO::Compress::Bzip2: 2.008
  IO::Compress::Gzip: 2.008
  IPC::Run3: 0.042
  Mouse: 0.93
  Params::Util: 0.35
  Time::Elapsed: 0.24
  Time::HiRes: 1.9709
  perl: 5.8.5
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Xtract
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Xtract
version: 0.15
